/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.abdullah;

import JSSC.SerialPort;
import JSSC.SerialPortException;
import java.awt.EventQueue;
import static java.lang.Math.random;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abdullah Sajid
 */
public class AddTest extends javax.swing.JFrame {

    String username;
    String test_name;
    /**
     * Creates new form AddTest
     */
    public AddTest() {
        this.setResizable(false);
//        saveButton.setVisible(false);
        initComponents();
        saveButton.setVisible(false);
    }
    public AddTest(String username, String testname) {
        this.username = username;
        this.test_name = testname;
        this.setResizable(false);
        initComponents();
        saveButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        two = new javax.swing.JLabel();
        second_value = new javax.swing.JLabel();
        third_value = new javax.swing.JLabel();
        fourth_value = new javax.swing.JLabel();
        fifth_value = new javax.swing.JLabel();
        sixth_value = new javax.swing.JLabel();
        first_value = new javax.swing.JLabel();
        one = new javax.swing.JLabel();
        three = new javax.swing.JLabel();
        four = new javax.swing.JLabel();
        six = new javax.swing.JLabel();
        five = new javax.swing.JLabel();
        counter = new javax.swing.JLabel();
        readyLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Callibrated Reading");
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(26, 141, 207));

        two.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        two.setForeground(new java.awt.Color(255, 255, 255));
        two.setText("0");

        second_value.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        second_value.setText("Second Value");

        third_value.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        third_value.setText("Third Value");

        fourth_value.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        fourth_value.setText("Fourth Value");

        fifth_value.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        fifth_value.setText("Fifth Value");

        sixth_value.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        sixth_value.setText("Sixth Value");

        first_value.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        first_value.setText("First Value");

        one.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        one.setForeground(new java.awt.Color(255, 255, 255));
        one.setText("0");

        three.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        three.setForeground(new java.awt.Color(255, 255, 255));
        three.setText("0");

        four.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        four.setForeground(new java.awt.Color(255, 255, 255));
        four.setText("0");

        six.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        six.setForeground(new java.awt.Color(255, 255, 255));
        six.setText("0");

        five.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        five.setForeground(new java.awt.Color(255, 255, 255));
        five.setText("0");

        counter.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 48)); // NOI18N
        counter.setText("0");

        readyLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        readyLabel.setForeground(new java.awt.Color(229, 37, 49));
        readyLabel.setText("Get Ready");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sixth_value)
                    .addComponent(fifth_value)
                    .addComponent(fourth_value)
                    .addComponent(third_value)
                    .addComponent(second_value)
                    .addComponent(first_value))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(three)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(readyLabel)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(five)
                            .addComponent(one)
                            .addComponent(six)
                            .addComponent(two)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(four)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(counter)
                        .addGap(166, 166, 166))))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(first_value)
                                    .addComponent(one))
                                .addGap(18, 18, 18)
                                .addComponent(second_value))
                            .addComponent(two))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(third_value)
                            .addComponent(three))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourth_value)
                            .addComponent(four))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fifth_value)
                            .addComponent(five))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sixth_value)
                            .addComponent(six)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(readyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(counter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(startButton)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new MainMenu().setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
class GoodWorkerThread extends Thread
		{ 
		  public GoodWorkerThread(JLabel label,JButton saveButton,JLabel one,JLabel two,JLabel three,JLabel four,JLabel five,JLabel six)
		  { 
		   this.label =label;
                   this.save_Button = saveButton;
                   this.on = one;
                   this.tw = two;
                   this.thre = three;
                   this.fou = four;
                   this.fiv = five;
                   this.si = six;
                   
		  }
		
		  public void run()
		  { 
		   try
                        {
                          for(i=10;i>=0;i--)
                          { 
                           EventQueue.invokeLater(new 
                             Runnable()
                             { 
                              public void run()
                                    { 
                                        String j = Integer.toString(i);
                                        System.out.println(j);
                                      label.setText(j);
                                    }
                             });
                           Thread.sleep(1000); 
                          }
                          double random = Math.random() * 280 + 1;
                          DecimalFormat df = new DecimalFormat("#.##");
                          String a = df.format(random);
                          random = Math.random() * 280 + 1;
                           String b = df.format(random);
                          random = Math.random() * 280 + 1;
                           String c = df.format(random);
                          random = Math.random() * 280 + 1;
                           String d = df.format(random);
                          random = Math.random() * 280 + 1;
                           String e = df.format(random);
                          random = Math.random() * 280 + 1;
                           String f = df.format(random);
                          on.setText(a);
                          tw.setText(b);
                          thre.setText(c);
                          fou.setText(d);
                          fiv.setText(e);
                          six.setText(f);
                          save_Button.setVisible(true);
                        }
		   catch (InterruptedException exception) {} 
		  }
                private  JLabel label;
                private  JLabel on;
                private  JLabel tw;
                private  JLabel thre;
                private  JLabel fou;
                private  JLabel fiv;
                private  JLabel si;
                private JButton save_Button;
                private int i;
}
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
         startButton.setVisible(false);
         // swing can not be updated by any thread except event dipatch thread which exceutes swing gui so we need to use worker thread to update GUI
         // save button becomes visible too early bcz the worker thread executes asyncronously so we will display button after worker thred executes
        // see http://www.informit.com/articles/article.aspx?p=26326&seqNum=9
         new GoodWorkerThread(counter,saveButton,one,two,three,four,five,six).start();
    
             
    }//GEN-LAST:event_startButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
           SQLiteConnectivity sqlite = new SQLiteConnectivity();
           Statement st = null;
           ResultSet rs = null;
        try{
            String on = one.getText();
            String tw = two.getText();
            String thre = three.getText();
            String fou = four.getText();
            String fiv = five.getText();
            String si = six.getText();
            
            
            Connection connection = sqlite.connect();
            st= connection.createStatement();
                int p =st.executeUpdate("insert into tests(username,test_name) values('"+username+"','"+test_name+"');");
             
                if(p==1){
                    
                     rs =st.executeQuery("Select * from tests where test_name='"+test_name+"'");
                     int test_id= (int)rs.getObject(1) ;
                     int q =st.executeUpdate("insert into calibration_reading(test_id,first_reading,second_reading,third_reading,fourth_reading,fifth_reading,sixth_reading) values('"+test_id+"','"+on+"','"+tw+"','"+thre+"','"+fou+"','"+fiv+"','"+si+"');");
                     st.close();
                     sqlite.disconnect();
                     if(q==1){
                    //close this window
                    new MainMenu(username).setVisible(true);
                    setVisible(false);
                    dispose();
                     }
               
                    //Open the menu window
                    //new SplashScreen().setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(null,"There occurs an error","Error",JOptionPane.ERROR_MESSAGE);
                }
           
            
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"There occurs an error, Please ensure that there is not any error","Error",JOptionPane.ERROR_MESSAGE);
            System.err.println(e);
        }
//         SerialPort serialport = new SerialPort("COM5");
//        try{
//            serialport.openPort();
//            serialport.setParams(9600, 8, 1, 0);
////            String a;
////            a = in.next();
//            
////           while(true){
////            serialport.writeString(a);
////             Thread.sleep(5000);
////            }
//            String a=null;
//            for (int i = 0; i < 1; i++) {
//               
//            a = serialport.readString();
//            System.out.println(a);
//
//
//           } 
//            Thread.sleep(2000);
//            String readings[]= a.split(",");
//
//
//
//          
//        }
//        catch(SerialPortException ex){
//            System.err.println(ex);
//        } catch (InterruptedException ex) {
//          Logger.getLogger(AddTest.class.getName()).log(Level.SEVERE, null, ex);
//       }
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel counter;
    private javax.swing.JLabel fifth_value;
    private javax.swing.JLabel first_value;
    private javax.swing.JLabel five;
    private javax.swing.JLabel four;
    private javax.swing.JLabel fourth_value;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel one;
    private javax.swing.JLabel readyLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel second_value;
    private javax.swing.JLabel six;
    private javax.swing.JLabel sixth_value;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel third_value;
    private javax.swing.JLabel three;
    private javax.swing.JLabel two;
    // End of variables declaration//GEN-END:variables
}
